# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:821937749725:android:29b2741a5d2d01eedfa534",
    firebase_cli_token: "1//03wLs32CDxBpwCgYIARAAGAMSNwF-L9IrGXmf0KIdOWsaPDsZuqJJVEua7wd6doTKhyWAW4Z635ojCJsv3LVzXVcbOEq7cc_8B34",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "mohammedadel9yc@gmail.com",
    release_notes: "Frist Fastlane Firebase Distribution "
  )
    
  end
end
